### ISSUE TITLE
Look at boolean values

### ISSUE THREAD

**Issue by dmikusa** [paketo-buildpacks/jprofiler#120]
## Expected Behavior

The values for `BPL_JPROFILER_ENABLED` and `BP_JPROFILER_ENABLED` are ignored by the buildpack. It only looks to see if those env variables are set. It should also check the contents of those variables.

## Current Behavior

https://stackoverflow.com/questions/79120907/added-jprofiler-buildpack-to-spring-boot-app-not-honoring-bpl-flag

## Possible Solution

Read the state of the env variable and ensure it's true/false, use that value to make the decision.

1. Happens here -> https://github.com/paketo-buildpacks/jprofiler/blob/main/helper/properties.go#L33-L35. This can be fixed by switching to use libpak's https://github.com/paketo-buildpacks/libpak/blob/main/sherpa/env_var.go#L57 helper.
2.  Happens here -> https://github.com/paketo-buildpacks/jprofiler/blob/main/jprofiler/detect.go#L34-L36. This can be fixed by switching to use libpak's https://github.com/paketo-buildpacks/libpak/blob/fca783c620a5a2a82ae104f71101aaca411b4855/buildpack.go#L442-L450

**Comment by jakesmolka** [comment]
Thanks @dmikusa, also for the great explanation on stackoverflow. I created a PR. Please note that I'm not used to Golang (anymore).
